version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-bank
    platform: linux/arm64/v8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r!
      MYSQL_DATABASE: bank
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1q2w3e4r!"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local
