jwt:
  secret-key : "lecture"
  time : 30


oauth2:
  providers:
    google:
      client-id :
      client-secret :
      redirect-uri : http://localhost:9090/api/v1/auth/callback
    github:
      client-id:
      client-secret:
      redirect-uri: http://localhost:9090/api/v1/auth/callback

database:
  mysql:
    url : jdbc:mysql://localhost:3306/bank?useSSL=false&serverTimezone=UTC
    username : root
    password : 1q2w3e4r!
    driver-class-name : com.mysql.cj.jdbc.Driver

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9090
